spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcache?serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: qwe`123
  cache:
    redis:
      key-prefix: boot_


logging:
  level:
    com:
      example:
        mapper:
          UserMapper: debug

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity